version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.fastapi  # Dockerfile for FastAPI
    container_name: fastapi_backend
    ports:
      - "8000:8000"  # Expose FastAPI on localhost:8000
    volumes:
      - ./app:/app  # Mount backend code for live updates
    restart: always  # Restart container if it crashes

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.streamlit  # Dockerfile for Streamlit
    container_name: streamlit_frontend
    ports:
      - "8501:8501"  # Expose Streamlit on localhost:8501
    depends_on:
      - backend  # Ensure backend starts before frontend
    volumes:
      - ./frontend:/frontend  # Mount frontend code for live updates
    restart: always  # Restart container if it crashes

