name: CI Pipeline

on:
  push:
    branches:
      - main  
 # pull_request:  

jobs:
  ci:
    runs-on: ubuntu-latest  

    steps:
      # 1. Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3  

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'  

      # 3. Cache pip dependencies
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 4. Install Dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_streamlit.txt  
          pip install -r requirements_fastapi.txt    

      # 5. Run Tests
      - name: Run Tests
        run: |
          echo "No tests available yet."  # 👉 Placeholder since no tests yet

      # 6. Run Static Code Analysis
      - name: Run Static Code Analysis
        run: |
          pip install flake8
          flake8 app/fastapi app/streamlit --max-line-length=88

  
